---
- name: Deploy Jenkins
  openshift_raw:
    state: present
    definition: "{{ lookup('template', '{{ role_path }}/templates/{{ item }}') | from_yaml }}"
  loop:
    - jenkins-secret.yaml
    - jenkins-service.yaml
    - jenkins-pvc.yaml
    - jenkins-route.yaml
    - jenkins.yaml
