FROM quay.io/kubevirtci/golang:v20241213-57bd934 as builder
ENV GOPROXY=https://proxy.golang.org|direct \
    GOFLAGS="-mod=vendor -ldflags=-extldflags=\"-static\"" \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
ENV GIMME_GO_VERSION=1.23.4
RUN mkdir kubevirt && \
    cd kubevirt && \
    git clone https://github.com/kubevirt/project-infra.git && \
    cd project-infra && \
    /usr/local/bin/runner.sh /bin/sh -c "env GOPROXY=off go build -tags netgo -o /go/bin/test-subset ./external-plugins/test-subset/plugin/main.go"

FROM gcr.io/k8s-prow/git:v20240729-4f255edb07
COPY --from=builder /go/bin/test-subset /usr/bin/test-subset
ENTRYPOINT ["/usr/bin/test-subset"]
