apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-daemon-mirror-config
data:
  docker: |
{{ dockerDaemonConfig | indent(width=4, indentfirst=True) }}

  docker-proxy: |
{{ dockerDaemonProxyConfig | indent(width=4, indentfirst=True) }}
