---
resources:
  - resources/deployment.yaml
  - resources/service.yaml

images:
  - name: ghcr.io/rpardini/docker-registry-proxy:0.6.2
    newName: quay.io/kubevirtci/rpardini-docker-registry-proxy
    # Include workaround for https://github.com/rpardini/docker-registry-proxy/issues/181
    newTag: 0.6.2-ssl-verify-depth-3

configMapGenerator:
  - &mirror_proxy_config
    name: mirror-proxy-config
    namespace: kubevirt-prow
    files:
      - configs/ca.crt
  - <<: *mirror_proxy_config
    namespace: kubevirt-prow-jobs
  - name: docker-daemon-mirror-config
    namespace: kubevirt-prow-jobs
    files:
      - configs/docker
      - configs/docker-proxy

secretGenerator:
  - name: docker-mirror-proxy
    namespace: kubevirt-prow
    files:
      - ca.key=secrets/ca.key
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true
