---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-config
type: Opaque
stringData:
  grafana.ini: |
    # nothing right now
    [security]
    admin_user = {{ grafanaUser }}
    admin_password = {{ grafanaPassword }}

    [auth.anonymous]
    enabled = true
    org_name = Main Org.
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus
      version: 1
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10 #how often Grafana will scan for changed dashboards
      options:
        path: /var/lib/grafana/dashboards
