---
apiVersion: v1
kind: Route
metadata:
  name: grafana
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  host: "{{ grafanaUrl }}"
  tls:
    termination: edge
  to:
    kind: Service
    name: grafana
    weight: 100
  wildcardPolicy: None
