---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ci-usage-exporter
  labels:
    group: kubevirtci
spec:
  selector:
    matchLabels:
      app: ci-usage-exporter
  endpoints:
  - port: metrics
