---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: common
  labels:
    group: kubevirtci
spec:
  selector:
    matchLabels:
      monitoring: "true"
  endpoints:
  - port: metrics
