---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway
  labels:
    group: kubevirtci
spec:
  selector:
    matchLabels:
      app: pushgateway
  endpoints:
  - port: pushgateway
