{
 "title": "Bazel Cache",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Bazel Remote Cache Hits / Misses (thirty minute increase)",
   "type": "graph",
   "description": "Cache hit rates for Kubernetes's https://github.com/kubernetes/test-infra/tree/master/greenhouse deployment",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "hit rate (last thirty minutes)" }
   ],
   "targets": [
    {
     "expr": "increase(bazel_cache_action_hits[30m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Action Cache hits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "increase(bazel_cache_cas_hits[30m])",
     "legendFormat": "Content Addressed Storage hits"
    },
    {
     "expr": "increase(bazel_cache_action_misses[30m])",
     "legendFormat": "Action Cache misses"
    },
    {
     "expr": "increase(bazel_cache_cas_misses[30m])",
     "legendFormat": "Content Addressed Storage misses"
    },
    {
     "expr": "clamp_min(increase(bazel_cache_action_hits[30m]) / (increase(bazel_cache_action_hits[30m]) + increase(bazel_cache_action_misses[30m])) * 100, 0)",
     "legendFormat": "Action Cache Hit Rate"
    },
    {
     "expr": "clamp_min(increase(bazel_cache_cas_hits[30m]) / (increase(bazel_cache_cas_hits[30m]) + increase(bazel_cache_cas_misses[30m])) * 100, 0)",
     "legendFormat": "Content Addressed Storage Hit Rate"
    }
   ]
  },
  {
   "title": "Content Cache Hits (CAS)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "bazel_cache_cas_hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Content Cache Misses (CAS)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "bazel_cache_cas_misses",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Action Cache Hits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "bazel_cache_action_hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Action Cache Misses",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "bazel_cache_action_misses",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bazel Remote Cache Disk Usage",
   "type": "graph",
   "description": "Disk usage for Kubernetes's https://github.com/kubernetes/test-infra/tree/master/greenhouse deployment",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bazel_cache_disk_free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "free",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expr": "bazel_cache_disk_used", "legendFormat": "used" },
    { "expr": "bazel_cache_disk_total", "legendFormat": "total disk size" },
    {
     "expr": "bazel_cache_disk_free / bazel_cache_disk_total * 100",
     "legendFormat": "percent free"
    }
   ]
  },
  {
   "title": "Last Evicted Entry Access Age",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "hours" }
   ],
   "targets": [
    {
     "expr": "bazel_cache_last_evicted_access_age",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "last evicted entry access age (hours)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "GitHub Cache",
 "description": "Metrics from the GitHub API reverse proxy HTTP cache in the Prow cluster.",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Cache Requests (per hour)",
   "type": "graph",
   "description": "Count of cache requests of each cache mode over the last hour.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses[1h])) by (mode)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h]))",
     "legendFormat": "(No Cost)"
    }
   ]
  },
  {
   "title": "Cache Efficiency",
   "type": "graph",
   "description": "Percentage of cacheable requests that are fulfilled for free.\nNo cost modes are \"COALESCED\" and \"REVALIDATED\".\nCacheable modes include the no cost modes, \"CHANGED\" and \"MISS\".",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    {
     "format": "percentunit",
     "label": "% Cacheable Request Fulfilled for Free"
    }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h])) \n/ sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED|MISS|CHANGED\"}[1h]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Efficiency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "kubevirt-bot GitHub API(v3) Token Usage",
   "type": "graph",
   "description": "The number of API calls the kubevirt-bot has used against its rate limit of 5000 per hour.\nNote that this is slightly different from a sliding window of API calls made in the past hour which could pass 5000 if the time period straddles a ratelimit reset time.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "API Ratelimit Tokens Used" }
   ],
   "targets": [
    {
     "alias": "Tokens used",
     "expr": "github_token_count{login=\"kubevirt-bot\"}",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "Tokens used",
     "measurement": "github_token_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "login", "operator": "=", "value": "kubevirt-bot" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(ghcache_disk_used/(ghcache_disk_used+ghcache_disk_free)) without(instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "% Used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(ghcache_disk_used) without(instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "GB Used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(ghcache_disk_free) without(instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "GB Free",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API Tokens Saved: Last hour",
   "type": "singlestat",
   "description": "The number of no cost requests in the last hour.\nThis includes both \"COALESCED\" and \"REVALIDATED\" modes.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API Tokens Saved: Last 7 days",
   "type": "singlestat",
   "description": "The number of no cost requests in the last 7 days.\nThis includes both \"COALESCED\" and \"REVALIDATED\" modes.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[7d]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "CI Infrastructure Utilization",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total Gib * hour per lane in the last 24h",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "((job_name_repo_type:kubevirt_ci_job_memory_bytes_all:sum * on(job_name) group_left job_name:prow_job_runtime_seconds_sum:increase24h) > 0) / ( 3600 * 1024 * 1024 * 1024)"
    }
   ]
  },
  {
   "title": "Historical memory utilization in the workloads cluster",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(instance:node_uname_info:sum{cluster=\"prow-workloads\", nodename=~\"bare-metal-.*\"} * on(instance) group_left instance:node_used_memory:sum )",
     "legendFormat": "Total memory used "
    },
    {
     "expr": "sum(sum without(cluster,container,domainname,endpoint,job,machine,namespace,nodename,pod,prometheus,prometheus_replica,release,service,sysname,version) (node_uname_info{cluster=\"prow-workloads\",nodename=~\"bare-metal.*\"}) * on(instance) group_left sum by(instance)(node_memory_MemTotal_bytes) )",
     "legendFormat": "Total memory available"
    }
   ]
  },
  {
   "title": "Total Gib * h capacity in the last 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(instance:node_uname_info:sum{cluster=\"prow-workloads\", nodename=~\"bare-metal-.*\"} * on(instance) group_left instance:node_memory:sum) * 24 * 0.96 / (1024 * 1024 * 1024)"
    }
   ]
  },
  {
   "title": "Gib * h per full PR build in the last 24h ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "none:prow_memoryhour_per_job:mean24h"
    }
   ]
  },
  {
   "title": "Full PR build capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(instance:node_uname_info:sum{cluster=\"prow-workloads\", nodename=~\"bare-metal-.*\"} * on(instance) group_left instance:node_memory:sum) * 24 * 0.96 / (1024 * 1024 * 1024)) / sum(none:prow_memoryhour_per_job:mean24h)"
    }
   ]
  },
  {
   "title": "Average utilization in the last 24h",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (((job_name_repo_type:kubevirt_ci_job_memory_bytes_all:sum * on(job_name) group_left job_name:prow_job_runtime_seconds_sum:increase24h) > 0) / ( 3600 * 1024 * 1024 * 1024)) / (24 * 10 * 225)) * 100"
    }
   ]
  },
  {
   "title": "Average utilization in the last 6h",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (((job_name_repo_type:kubevirt_ci_job_memory_bytes_all:sum * on(job_name) group_left job_name:prow_job_runtime_seconds_sum:increase6h) > 0) / ( 3600 * 1024 * 1024 * 1024)) / (6 * 10 * 225)) * 100"
    }
   ]
  },
  {
   "title": "Average utilization in the last 3h",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (((job_name_repo_type:kubevirt_ci_job_memory_bytes_all:sum * on(job_name) group_left job_name:prow_job_runtime_seconds_sum:increase3h) > 0) / ( 3600 * 1024 * 1024 * 1024)) / (3 * 10 * 225)) * 100"
    }
   ]
  }
 ]
}
{
 "title": "Prow job load",
 "tags": [
  "prow",
  "load"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job_name", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Average utilization in the last 3h",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (((job_name_repo_type:kubevirt_ci_job_memory_bytes_all:sum * on(job_name) group_left job_name:prow_job_runtime_seconds_sum:increase3h) > 0) / ( 3600 * 1024 * 1024 * 1024)) / (3 * 10 * 225)) * 100"
    }
   ]
  },
  {
   "title": "prowjobs in queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (clamp_min(prowjobs{state=~\"triggered\", job_name=~\"${job_name}\"},0))"
    }
   ]
  },
  {
   "title": "prowjobs in queue",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (prowjobs{state=\"triggered\", job_name=~\"${job_name}\"})"
    }
   ]
  },
  {
   "title": "prowjobs running",
   "type": "graph",
   "gridPos": { "h": 6, "w": 22, "x": 2, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (prowjobs{state=~\"pending\", job_name=~\"${job_name}\"})"
    }
   ]
  },
  {
   "title": "prowjobs running",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (prowjobs{state=\"pending\", job_name=~\"${job_name}\"})"
    }
   ]
  },
  {
   "title": "new failed jobs / 15m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (clamp_min(delta(prowjobs{state=~\"failure\", job_name=~\"${job_name}\"}[15m]),0))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "failed jobs %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum (prowjobs{state=~\"failure\", job_name=~\"${job_name}\"})) / \n(sum (prowjobs{state=\"failure\", job_name=~\"${job_name}\"}) + sum (prowjobs{state=\"success\", job_name=~\"${job_name}\"}))"
    }
   ]
  }
 ]
}
{
 "title": "Flaky Tests: kubevirt/kubevirt",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "max flakes overall",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum (avg_over_time(flakefinder_report_e2e_test_failed{date_range=\"024h\", severity=~\"(red|orange|yellow)\", test_lane=~\"pull-.*\"}[1m]))",
     "legendFormat": "presubmits"
    },
    {
     "expr": "sum (avg_over_time(flakefinder_report_e2e_test_failed{date_range=\"024h\", severity=~\"(red|orange|yellow)\", test_lane=~\"periodic-.*\"}[1m]))",
     "legendFormat": "periodics"
    }
   ]
  },
  {
   "title": "sig presubmits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum by (severity) (flakefinder_report_e2e_test_failed{date_range=\"024h\", severity=~\"(red|orange|yellow)\", test_lane=~\"pull-.*storage.*\"})",
     "legendFormat": "storage {{severity}}"
    },
    {
     "expr": "sum by (severity) (flakefinder_report_e2e_test_failed{date_range=\"024h\", severity=~\"(red|orange|yellow)\", test_lane=~\"pull-.*(compute|operator).*\"})",
     "legendFormat": "compute {{severity}}"
    },
    {
     "expr": "sum by (severity) (flakefinder_report_e2e_test_failed{date_range=\"024h\", severity=~\"(red|orange|yellow)\", test_lane=~\"pull-.*network.*\"})",
     "legendFormat": "network {{severity}}"
    }
   ]
  },
  {
   "title": "Links",
   "type": "text",
   "gridPos": { "h": 18, "w": 4, "x": 0, "y": 5 },
   "options": {
    "content": "# Links\n\n* [FlakeFinder entry page](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/index.html)\n* [testgrid entry page](https://testgrid.k8s.io/kubevirt)\n\n# Severity mapping\n\nThe severity of a flake describes the ratio of failed vs. succeeded tests.\nTo better visualize the severity we colorize the fields of the FlakeFinder\nreport according to the severity level of the flake.\n\n| Ratio   | Color        |                                       |\n| ------- | ------------ | ------------------------------------- |\n| > 50%   | red          | <span style=\"color: #ff8080\">■</span> |\n| > 20%   | orange       | <span style=\"color: #ffbf80\">■</span> |\n| > 10%   | yellow       | <span style=\"color: #ffff80\">■</span> |\n| > 0%    | almost green | <span style=\"color: #dfff80\">■</span> |\n| = 0%    | green        | <span style=\"color: #9fff80\">■</span> |\n"
   }
  },
  {
   "title": "presubmit lanes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sum by (test_lane, severity) (flakefinder_report_e2e_test_failed{date_range=\"024h\", severity=~\"(red|orange|yellow)\", test_lane=~\"pull-.*\"})",
     "legendFormat": "{{test_lane}} {{severity}}"
    }
   ]
  },
  {
   "title": "sig periodics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 18 },
   "targets": [
    {
     "expr": "sum by (severity) (flakefinder_report_e2e_test_failed{date_range=\"024h\", severity=~\"(red|orange|yellow)\", test_lane=~\"periodic-.*storage.*\"})",
     "legendFormat": "storage {{severity}}"
    },
    {
     "expr": "sum by (severity) (flakefinder_report_e2e_test_failed{date_range=\"024h\", severity=~\"(red|orange|yellow)\", test_lane=~\"periodic-.*(compute|operator).*\"})",
     "legendFormat": "compute {{severity}}"
    },
    {
     "expr": "sum by (severity) (flakefinder_report_e2e_test_failed{date_range=\"024h\", severity=~\"(red|orange|yellow)\", test_lane=~\"periodic-.*network.*\"})",
     "legendFormat": "network {{severity}}"
    }
   ]
  },
  {
   "title": "periodic lanes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 26 },
   "targets": [
    {
     "expr": "sum by (test_lane, severity) (flakefinder_report_e2e_test_failed{date_range=\"024h\", severity=~\"(red|orange|yellow)\", test_lane=~\"periodic-.*\"})",
     "legendFormat": "{{test_lane}} {{severity}}"
    }
   ]
  }
 ]
}