FROM quay.io/kubevirtci/golang:v20250701-f32dbda

ENV GIMME_GO_VERSION=1.24.4

RUN set -x && \
    git clone --depth 1 https://github.com/kubernetes/test-infra.git && \
    cd ./test-infra && \
    /usr/local/bin/runner.sh /bin/sh -ce 'go build -o ./robots/pr-creator/pr-creator ./robots/pr-creator/main.go' && \
    mv ./robots/pr-creator/pr-creator /usr/local/bin/ && \
    chmod +x /usr/local/bin/pr-creator && \
    /usr/local/bin/runner.sh /bin/sh -ce 'go clean -cache -modcache' && \
    cd .. && rm -rf ./test-infra

RUN set -x && \
    git clone --depth 1 https://github.com/kubevirt/project-infra.git && \
    cd ./project-infra && \
    chmod +x ./hack/*.sh && \
    cp ./hack/*.sh /usr/local/bin && \
    /usr/local/bin/runner.sh /bin/sh -ce 'go build -o /usr/local/bin/labels-checker ./robots/cmd/labels-checker' && \
    chmod +x /usr/local/bin/labels-checker && \
    cd .. && rm -rf ./project-infra

RUN dnf install -y \
        skopeo && \
    dnf -y clean all

ENV GIT_ASKPASS=/usr/local/bin/git-askpass.sh
