ARG ARCH
FROM bootstrap-$ARCH

ENV GIMME_GO_VERSION=1.26.4

COPY entrypoint.sh /usr/local/bin/
COPY golang.sh /etc/setup.mixin.d/

# Cache latest stable golang version
RUN curl -sL -o /bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme && chmod +x /bin/gimme
RUN GIMME_DEBUG=true gimme $GIMME_GO_VERSION
