linters:
  # initially we disable all linters, since this is an old code base with quite a lot of issues
  disable-all: true
  enable:
  - gocyclo
#  - staticcheck
#  - unused
#  - ineffassign
#  - govet
#  - gosimple
#  - errcheck
#linters-settings:
#  gocyclo:
#    min-complexity: 10
