run:
  modules-download-mode: readonly
  timeout: 5m
output:
  show-stats: true
linters:
  # initially we disable all linters, since this is an old code base with quite a lot of issues
  disable-all: true
  enable:
  - gocyclo
#  - staticcheck
  - unused
  - govet
  - ineffassign
  - gosimple
#  - errcheck
#linters-settings:
#  gocyclo:
#    min-complexity: 10
