version: "2"
run:
  go: "1.25"
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - gocyclo
    - govet
    - ineffassign
#    - staticcheck
    - unused
#  settings:
#    gocyclo:
#      min-complexity: 10