version: "2"
run:
  go: "1.25"
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - gocyclo
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    staticcheck:
      checks:
        - "all"
        - "-SA9003"
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        - "-ST1023"
        # TODO: re-enable following to re-enable default settings, thus config
        # will then be redundant
        - "-ST1001" # should not use dot imports
        - "-ST1005" # err formatting rule
        - "-QF100*"
        - "-QF1012" # replace WriteString with fmt.Fprintf
#    gocyclo:
#      min-complexity: 10