FROM quay.io/kubevirtci/golang:v20250701-f32dbda as builder
RUN cd /project-infra/ && \
    /usr/local/bin/runner.sh /bin/sh -c "env GOPROXY=off go build -tags netgo -o /go/bin/referee ./external-plugins/referee/main.go"

FROM gcr.io/k8s-prow/git:v20240729-4f255edb07
COPY --from=builder /go/bin/referee /usr/bin/referee
ENTRYPOINT ["/usr/bin/referee"]
