---
- op: replace
  path: /spec/template/spec/volumes/2/secret
  value:
    # Not using KubeVirt CI Prow GitHub App Credentials because the
    # cherry-picker plugin requires a user to create forks.
    secretName: github-token
