---
# sets resources
- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi

# scale up the deployment
- op: replace
  path: /spec/replicas
  value: 3

# inject jobs configmap
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --job-config-path=/etc/job-config

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: job-config
    mountPath: /etc/job-config
    readOnly: true

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: job-config
    configMap:
      name: job-config

# inject consolidated KUBECONFIG with federated clusters
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --kubeconfig=/etc/kubeconfig/config

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: kubeconfig
    mountPath: /etc/kubeconfig
    readOnly: true

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: kubeconfig
    secret:
      secretName: kubeconfig
      defaultMode: 420

# oauth configuration for PR Status and Abort/ReRun features
# https://docs.prow.k8s.io/docs/components/core/deck/github-oauth-setup/
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --github-oauth-config-file=/etc/githuboauth/secret

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: oauth-config
    mountPath: /etc/githuboauth
    readOnly: true

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: oauth-config
    secret:
      secretName: github-oauth-config

- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --oauth-url=/github-login

# https://docs.prow.k8s.io/docs/components/core/deck/csrf/
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --cookie-secret=/etc/cookie/secret

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: cookie-secret
    secret:
      secretName: cookie

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: cookie-secret
    mountPath: /etc/cookie
    readOnly: true

# add the Rerun button to the Rerun modal dialog
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --rerun-creates-job=true
