---
# KubeVirt Prow control-plane cluster does not provide IPv6 connectivity to Pods
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: DISABLE_IPV6
    value: "true"

# schedule on cachenode
- op: add
  path: /spec/template/spec/nodeSelector
  value:
    ci.kubevirt.io/cachenode: "true"
- op: add
  path: /spec/template/spec/tolerations
  value:
    - key: ci.kubevirt.io/cachenode
      operator: Exists
      effect: NoSchedule
