---
# scale up the deployment
- op: replace
  path: /spec/replicas
  value: 4

# inject jobs configmap
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --job-config-path=/etc/job-config

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: job-config
    mountPath: /etc/job-config
    readOnly: true

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: job-config
    configMap:
      name: job-config

# inject consolidated KUBECONFIG with federated clusters for the updateconfig plugin
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --kubeconfig=/etc/kubeconfig/config

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: kubeconfig
    mountPath: /etc/kubeconfig
    readOnly: true

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: kubeconfig
    secret:
      secretName: kubeconfig
      defaultMode: 420

# inject slack credentials for the slackevents plugin
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --slack-token-file=/etc/slack/token

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: slack-token
    mountPath: /etc/slack
    readOnly: true

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: slack-token
    secret:
      secretName: slack-token
