---
# sets resources
- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      cpu: 400m
      memory: 600Mi
    requests:
      cpu: 400m
      memory: 600Mi

# inject jobs configmap
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --job-config-path=/etc/job-config

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: job-config
    mountPath: /etc/job-config
    readOnly: true

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: job-config
    configMap:
      name: job-config

# inject consolidated KUBECONFIG with federated clusters
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --kubeconfig=/etc/kubeconfig/config

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: kubeconfig
    mountPath: /etc/kubeconfig
    readOnly: true

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: kubeconfig
    secret:
      secretName: kubeconfig
      defaultMode: 420
