---
# store tide status files in our GCS bucket
- op: replace
  path: /spec/template/spec/containers/0/args/6
  value: --status-path=gs://kubevirt-prow/tide-status

- op: replace
  path: /spec/template/spec/containers/0/args/7
  value: --history-uri=gs://kubevirt-prow/tide-history.json

# inject jobs configmap
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --job-config-path=/etc/job-config

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: job-config
    mountPath: /etc/job-config
    readOnly: true

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: job-config
    configMap:
      name: job-config
