FROM quay.io/kubevirtci/golang:v20260306-351d3b1 as builder
RUN cd /project-infra/ && \
    /usr/local/bin/runner.sh /bin/sh -ce "CGO_ENABLED=0 GOPROXY=off go build -tags netgo -o /go/bin/coverage ./external-plugins/coverage/plugin/main.go"

FROM gcr.io/k8s-prow/git:v20240729-4f255edb07
COPY --from=builder /go/bin/coverage /usr/bin/coverage
ENTRYPOINT ["/usr/bin/coverage"]
