---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ci-usage-exporter
  namespace: default
  name: ci-usage-exporter
spec:
  ports:
    - name: metrics
      port: 9836
  selector:
    app: ci-usage-exporter
