---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prow-exporter
  namespace: default
  name: prow-exporter
spec:
  selector:
    app: prow-exporter
  ports:
  - name: metrics
    port: 9090
