- command: update
  path: plank.job_url_template
  value: >-
    https://deck.prowdeploy.ci/view/gcs/kubernetes-prow/
    {{if eq .Spec.Type "presubmit"}}pr-logs/
    pull{{else if eq .Spec.Type "batch"}}pr-logs/
    pull{{else}}logs{{end}}{{if .Spec.Refs}}{{if ne .Spec.Refs.Org ""}}/
    {{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}{{end}}{{end}}{{if eq .Spec.Type "presubmit"}}/
    {{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/
    batch{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/
- command: update
  path: presets[2].volumes[0].hostPath.path
  value: /var/lib/stdci/shared/kubevirt-images/kubernetes-prow
- command: update
  path: prowjob_namespace
  value: kubernetes-prow-jobs
- command: update
  path: pod_namespace
  value: kubernetes-prow-jobs
- command: update
  path: plank.default_decoration_configs.*.gcs_configuration.bucket
  value: kubernetes-prow
- command: update
  path: deck.spyglass.gcs_browser_prefix
  value: https://gcsweb.prowdeploy.ci/gcs/
- command: update
  path: plank.default_decoration_configs.*.utility_images.clonerefs
  value: gcr.io/k8s-prow/clonerefs:v20210217-8c724915ff
- command: update
  path: plank.default_decoration_configs.*.utility_images.initupload
  value: gcr.io/k8s-prow/initupload:v20210217-8c724915ff
- command: update
  path: plank.default_decoration_configs.*.utility_images.entrypoint
  value: gcr.io/k8s-prow/entrypoint:v20210217-8c724915ff
- command: update
  path: plank.default_decoration_configs.*.utility_images.sidecar
  value: gcr.io/k8s-prow/sidecar:v20210217-8c724915ff
