apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-stack-kube-prom-prometheus
  namespace: default
spec:
  externalLabels:
    cluster: prow-workloads
    replica: "0"
  nodeSelector:
    ci.kubevirt.io/cachenode: "true"
  tolerations:
  - key: "ci.kubevirt.io/cachenode"
    operator: "Exists"
    effect: "NoSchedule"
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: ""
        selector:
          matchLabels:
            app: prometheus
            type: local
  additionalScrapeConfigs:
    name: prometheus-stack-kube-prom-prometheus-scrape-confg
    key: additional-scrape-configs.yaml
  thanos:
    baseImage: quay.io/thanos/thanos
    version: v0.21.1
    objectStorageConfig:
      key: thanos.yaml
      name: thanos-objstore-config
  resources:
    requests:
      memory: 4Gi
    limits:
      memory: 4Gi
