# Requires kustomize v3
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: gcs-credentials
    namespace: kubevirt-prow-jobs
    files:
      - secrets/service-account.json
    type: Opaque
  - name: bazel-cache-gcs
    namespace: kubevirt-prow-jobs
    files:
      - secrets/prow/google/service-accounts/bazel-cache/bazel-cache-sa.json
    type: Opaque
