# Requires kustomize v3
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: gcs
    namespace: kubevirt-prow-jobs
    files:
      - secrets/service-account.json
    type: Opaque
