- hosts: instance
  tasks:
    - name: set deploy environment
      set_fact:
        deploy_environment: 'kubevirtci-testing'

    - name: Include environment configuration
      include_vars:
        file: "{{ deploy_environment }}.yml"

    - name: Call deployment role own cleanup tasks.
      include_role:
        name: prow-deploy
      vars:
        main_actions:
          - cleanup
      ignore_errors: yes
