---
- hosts: instance
  tasks:
    - name: set deploy environment
      set_fact:
        deploy_environment: 'kubevirtci-testing'

    - name: Include environment configuration
      include_vars:
        file: "{{ deploy_environment }}.yml"

    - name: Include collection config
      include_vars:
        file: "collect.yml"

    - name: Include deployment
      block:
        - name: include prow-deploy role for testing
          include_role:
            name: prow-deploy
          vars:
            main_actions:
              - bootstrap
              - deploy

        - name: wait for deployment to settle
          include_tasks: retry-pod-status.yml
          vars:
            retries: 20
            delay: 10
      always:
        - name: collect deployment information
          include_tasks: collect.yml
