- hosts: instance
  tasks:
    - name: set deploy environment
      set_fact:
        deploy_environment: 'kubevirtci-testing'

    - name: Include staging config
      include_vars:
        file: "{{ deploy_environment }}.yml"

    - name: Tear down kubevirtci cluster
      command: kind delete cluster
      changed_when: false
      when: "'kubevirtci' in deploy_environment"
