---
driver:
  name: delegated

platforms:
  - name: instance  # must be able to `ssh host`, edit your ~/.ssh/config
    options:
      managed: False

provisioner:
  name: ansible

scenario:
  test_sequence:
    - prepare
    - converge
    - verify
