- hosts: instance
  tasks:
    - name: set deploy environment
      set_fact:
        deploy_environment: 'kubevirtci-testing'

    - name: load secrets
      include_vars:
        file: "../../vars/{{ deploy_environment }}/secrets.yml"

    - name: Include Deploy config
      include_vars:
        file: "{{ deploy_environment }}.yml"

    - name: Include smoke tests
      include_tasks: smoke_tests.yml
