FROM quay.io/kubevirtci/golang:v20251022-6eb3ab1 as builder

ENV GIMME_GO_VERSION=1.25.1

WORKDIR /workspace

RUN dnf install -y gpgme-devel device-mapper-devel btrfs-progs-devel

ENV GOPROXY=https://proxy.golang.org

COPY go.mod go.mod

COPY go.sum go.sum

RUN /usr/local/bin/runner.sh /bin/sh -c "go mod download"

COPY ./ ./

RUN /usr/local/bin/runner.sh /bin/sh -c "go build ."

FROM quay.io/kubevirtci/bootstrap:v20251022-6eb3ab1

WORKDIR /

RUN mkdir -p /var/lib/shared-images

COPY ./storage.conf /etc/containers/storage.conf

ENV PODMAN_IN_CONTAINER_ENABLED=true

COPY --from=builder /workspace/shared-images-controller .

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
