FROM quay.io/kubevirtci/golang:v20251218-e7a7fc9 as builder
ENV GOPROXY=https://proxy.golang.org|direct \
    GOFLAGS="-mod=vendor -ldflags=-extldflags=\"-static\"" \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
ENV GIMME_GO_VERSION=1.22.12
RUN mkdir kubevirt && \
    cd kubevirt && \
    git clone --depth=1 --branch main https://github.com/kubevirt/community.git && \
    cd community && \
    /usr/local/bin/runner.sh /bin/sh -ce "go mod vendor" && \
    /usr/local/bin/runner.sh /bin/sh -ce "env GOPROXY=off go build -tags netgo -o /go/bin/contributions ./generators/cmd/contributions"

FROM gcr.io/k8s-prow/git:v20240729-4f255edb07
COPY --from=builder /go/bin/contributions /usr/bin/contributions
ENTRYPOINT ["/usr/bin/contributions"]
