apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: prometheus-stack-kube-prom-alertmanager
  namespace: default
spec:
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path