FROM quay.io/kubevirtci/golang:v20260906-22dec7d
RUN /usr/local/bin/entrypoint.sh /bin/sh -ce "GOBIN=/usr/local/bin go install github.com/cancue/covreport@v0.5.0"
COPY --chmod=755 coverage-report.sh /usr/local/bin/coverage-report.sh

