apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: ghproxy
  name: ghproxy-cache
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: local
  local:
    path: /tmp/ghproxy
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node02
