---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kubevirt-prow-jobs
  name: crier
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
  - apiGroups:
      - prow.k8s.io
    resources:
      - prowjobs
    verbs:
      - get
      - watch
      - list
      - patch
