---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: prow-exporter
  labels:
    app: prow-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prow-exporter
  template:
    metadata:
      labels:
        app: prow-exporter
    spec:
      serviceAccountName: prow-exporter
      terminationGracePeriodSeconds: 30
      containers:
      - name: prow-exporter
        image: gcr.io/k8s-prow/exporter:v20240327-a58d781f5a
        imagePullPolicy: Always
        ports:
        - name: metrics
          containerPort: 9090
        - name: healthz
          containerPort: 8081
        args:
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        env:
        # Use KUBECONFIG envvar rather than --kubeconfig flag in order to provide multiple configs to merge.
        - name: KUBECONFIG
          value: "/etc/kubeconfig/config"
        volumeMounts:
        - mountPath: /etc/kubeconfig
          name: kubeconfig
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 15
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 100m
            memory: 500Mi
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: kubeconfig
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
