apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-stack-kube-prom-prometheus
  namespace: default
spec:
  externalLabels:
    cluster: ibm-prow-jobs
    replica: "0"
  resources:
    requests:
      cpu: 1
      memory: 12Gi
    limits:
      cpu: 1
      memory: 12Gi
