FROM quay.io/kubevirtci/golang:v20251218-e7a7fc9 as builder
ENV GOPROXY=https://proxy.golang.org|direct \
    GOFLAGS="-mod=vendor -ldflags=-extldflags=\"-static\"" \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
ENV GIMME_GO_VERSION=1.23.4
RUN mkdir -p kubernetes/test-infra && \
    cd kubernetes/test-infra && \
    git init && \
    git remote add origin https://github.com/kubernetes/test-infra.git && \
    git fetch origin 5abb19fd84c5169e1819572c55c5f993a7067d88 && \
    git reset --hard 5abb19fd84c5169e1819572c55c5f993a7067d88 && \
    /usr/local/bin/runner.sh /bin/sh -ce "go mod vendor" && \
    /usr/local/bin/runner.sh /bin/sh -ce "env GOPROXY=off go build -tags netgo -o /go/bin/migratestatus ./maintenance/migratestatus"

FROM gcr.io/k8s-prow/git:v20240729-4f255edb07
COPY --from=builder /go/bin/migratestatus /usr/bin/migratestatus
ENTRYPOINT ["/usr/bin/migratestatus"]
