FROM quay.io/kubevirtci/golang:v20250930-85e32e0 as builder
ENV GOPROXY=https://proxy.golang.org|direct \
    GOFLAGS="-mod=vendor -ldflags=-extldflags=\"-static\"" \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
ENV GIMME_GO_VERSION=1.25.1
RUN mkdir kubevirt && \
    cd kubevirt && \
    git clone https://github.com/kubevirt/project-infra.git && \
    cd project-infra && \
    /usr/local/bin/runner.sh /bin/sh -ce "env GOPROXY=off go build -tags netgo -o /go/bin/ginkgo ./robots/cmd/ginkgo"
RUN dnf install -y \
    ripgrep
FROM gcr.io/k8s-prow/git:v20240729-4f255edb07
COPY --from=builder /go/bin/ginkgo /usr/bin/ginkgo
COPY --from=builder /usr/bin/rg /usr/bin/rg
ENTRYPOINT ["/usr/bin/ginkgo"]
