# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_url = "http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1802_01.Libvirt.box"

  if Vagrant.has_plugin?("vagrant-cachier") then
      config.cache.scope = :machine
      config.cache.auto_detect = false
      config.cache.enable :dnf
      config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=4', 'tcp']
    }
  end

  config.vm.provider :libvirt do |domain|
      domain.cpus = 2
      domain.nested = true  # enable nested virtualization
      domain.cpu_mode = "host-model"
  end
 
  config.ssh.insert_key = false


  config.vm.define "jenkins-master" do |master|
      master.vm.hostname = "master"
      master.vm.network "private_network", ip: "192.168.201.2"
      master.vm.provider :libvirt do |domain|
          domain.memory = 1024
      end
      master.vm.provision "ansible" do |ansible|
        ansible.playbook = "ci.yaml"
        ansible.groups = {
          "jenkins-master" => ["jenkins-master"],
          "jenkins-slaves" => ["jenkins-master"],
        }
        ansible.host_vars = {
          "jenkins-master" => {"swarmRootDir" => "/var/lib/swarm"},
        }
      end
  end

  config.vm.define "jenkins-slaves" do |slave|
      slave.vm.hostname = "slave"
      slave.vm.network "private_network", ip: "192.168.201.3"
      slave.vm.provider :libvirt do |domain|
          domain.memory = 1024
      end
      slave.vm.provision "ansible" do |ansible|
        ansible.playbook = "ci.yaml"
        ansible.host_vars = {
          "jenkins-slaves" => {"labels" => "windows test test1"},
        }
      end
  end

  config.vm.define "store" do |store|
      store.vm.hostname = "store"
      store.vm.network "private_network", ip: "192.168.201.4"
      store.vm.provider :libvirt do |domain|
          domain.memory = 1024
      end

      # fedorapeople has python already installed, but our VM not
      store.vm.provision "shell", inline: <<-SHELL
        #!/bin/bash
        sudo yum install -y python2 libselinux-python
      SHELL

      store.vm.provision "ansible" do |ansible|
        ansible.playbook = "ci.yaml"
      end
  end
end
