# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.configure(2) do |config|
  config.vm.box = "fedora26"
  config.vm.box_url = "http://mirror.de.leaseweb.net/fedora/linux/releases/26/CloudImages/x86_64/images/Fedora-Cloud-Base-Vagrant-26-1.5.x86_64.vagrant-libvirt.box"

  if Vagrant.has_plugin?("vagrant-cachier") then
      config.cache.scope = :machine
      config.cache.auto_detect = false
      config.cache.enable :dnf
      config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=4', 'tcp']
    }
  end

  config.vm.provider :libvirt do |domain|
      domain.cpus = 2
      domain.nested = true  # enable nested virtualization
      domain.cpu_mode = "host-model"
  end
 
  config.ssh.insert_key = false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ci.yaml"
  end 

  config.vm.define "jenkins-master" do |master|
      master.vm.hostname = "master"
      master.vm.network "private_network", ip: "192.168.201.2"
      master.vm.provider :libvirt do |domain|
          domain.memory = 1024
      end
  end

  config.vm.define "jenkins-slaves" do |master|
      master.vm.hostname = "slave"
      master.vm.network "private_network", ip: "192.168.201.3"
      master.vm.provider :libvirt do |domain|
          domain.memory = 1024
      end
  end

  config.vm.define "store" do |master|
      master.vm.hostname = "store"
      master.vm.network "private_network", ip: "192.168.201.4"
      master.vm.provider :libvirt do |domain|
          domain.memory = 1024
      end
      master.vm.provision "ansible" do |ansible|
        ansible.playbook = "ci.yaml"
      end
  end
end
