---
- name: copy production kustomize files
  copy:
    src: '{{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/{{ item }}'
    dest: '{{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/{{ deploy_environment }}'
  delegate_to: '{{ inventory_hostname }}'
  loop:
    - kustomization.yaml
    - patches
    - resources

- name: prepare production resources for testing usage
  block:
    - name: patch ghproxy pvc class
      shell: |
        yq -i '.spec.storageClassName = "local"' {{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/{{ deploy_environment }}/patches/StrategicMerge/ghproxy.yaml
    - name: patch greenhouse and docker-mirror-proxy pvc size
      shell: |
        yq -i '.spec.resources.requests.storage = "10Gi"' {{ project_infra_root }}/github/ci/prow-deploy/kustom/components/greenhouse/pv/resources/pvc.yaml
        yq -i '.spec.resources.requests.storage = "10Gi"' {{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/{{ deploy_environment }}/resources/docker-mirror-proxy_pvc.yaml
    - name: patch ingresses
      shell: |
        yq -i '. *d load("{{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/{{ deploy_environment }}/{{ item[1] }}")' {{ project_infra_root }}/github/ci/prow-deploy/kustom/base/{{ item[0] }}
        yq -i 'del(.spec.tls[0].secretName)' {{ project_infra_root }}/github/ci/prow-deploy/kustom/base/{{ item[0] }}
      loop:
        - [manifests/upstream/prow_ingress.yaml, patches/StrategicMerge/prow-ingress.yaml]
        - [manifests/local/gcsweb-ingress.yaml, patches/StrategicMerge/gcsweb-ingress.yaml]
    - name: remove resource patching
      shell: |
        for component in deck prow_controller_manager; do
          yq -i 'map(select(.path != "/spec/template/spec/containers/0/resources"))' {{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/{{ deploy_environment }}/patches/JsonRFC6902/${component}_deployment.yaml
        done
        yq -i '[]' {{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/{{ deploy_environment }}/patches/JsonRFC6902/prow_ingress.yaml

    - name: Create kubeconfig secret
      copy:
        src: '{{ kubeconfig_path }}'
        dest: '{{ secrets_dir }}/kubeconfig'
        remote_src: true
