---
- name: Create secrets dir
  file:
    path: '{{ secrets_dir }}'
    state: directory

- name: set gcs service account
  set_fact:
    gcsServiceAccount: '{{ lookup("env", "GOOGLE_APPLICATION_CREDENTIALS") }}'
- name: Check GOOGLE_APPLICATION_CREDENTIALS env var
  fail:
    msg: GOOGLE_APPLICATION_CREDENTIALS must be set
  when: gcsServiceAccount is undefined or gcsServiceAccount == ""

- name: Create GCS secret
  copy:
    src: '{{ gcsServiceAccount }}'
    dest: '{{ secrets_dir }}/service-account.json'

- name: Create Virtualization CI GCS secret
  copy:
    content: '{{ virtciGCSServiceAccount }}'
    dest: '{{ secrets_dir }}/virtci-service-account.json'

# https://docs.prow.k8s.io/docs/components/core/deck/github-oauth-setup/
- name: Create Github OAuth config secret
  copy:
    content: |-
      client_id: {{ github_app_client_id }}
      client_secret: {{ github_app_client_secret }}
      redirect_url: https://{{ prowUrl }}/github-login/redirect
      final_redirect_url: https://{{ prowUrl }}/pr
    dest: '{{ secrets_dir }}/github-oauth-config'
  vars:
     github_app_client_id: >-
       {{ lookup("ansible.builtin.file", secrets_dir + '/github/client-id') | string }}
     github_app_client_secret: >-
       {{ lookup("ansible.builtin.file", secrets_dir + '/github/client-secret') | string }}

- name: Create kubeconfig secret
  when: kubeconfig is defined
  block:
    - name: Create kubeconfig file
      copy:
        content: '{{ kubeconfig }}'
        dest: '{{ kubeconfig_path }}'

- name: Create docker proxy CA key
  copy:
    content: '{{ dockerMirrorProxyCA.key }}'
    dest: '{{ components_dir }}/docker-mirror-proxy/base/secrets/ca.key'

- name: Create docker credentials secret
  template:
    src: docker_credentials.j2
    dest: '{{ secrets_dir }}/kubevirtci-docker-credential'

- name: Create quay credentials secret
  template:
    src: quay_credentials.j2
    dest: '{{ secrets_dir }}/kubevirtci-quay-credential'

- name: Create installer pull token secret
  copy:
    content: '{{ installerPullToken }}'
    dest: '{{ secrets_dir }}/kubevirtci-installer-pull-token'

- name: Create commenter oauth token secret
  copy:
    content: '{{ githubCommenterToken }}'
    dest: '{{ secrets_dir }}/commenter-oauth-token'

- name: Create coveralls token secret
  copy:
    content: '{{ coverallsToken }}'
    dest: '{{ secrets_dir }}/kubevirtci-coveralls-token'

- name: Create containerized-data-importer coveralls token
  copy:
    content: '{{ containerizedDataImporterCoverallsToken }}'
    dest: '{{ secrets_dir }}/containerized-data-importer-coveralls-token'

- name: Create win-sysprep-001 secret
  copy:
    content: '{{ windowsProductKeys["sysprep-001"] }}'
    dest: '{{ secrets_dir }}/win-sysprep-001'

- name: Create FOSSA token secret
  copy:
    content: '{{ fossaToken }}'
    dest: '{{ secrets_dir }}/kubevirtci-fossa-token'

- name: Create Prow GitHub Kubevirtbot SSH private key secret
  copy:
    content: '{{ prowKubevirtbotSSHPrivateKey }}'
    dest: '{{ secrets_dir }}/prow-kubevirtbot-github-ssh-secret'
