---
# setup data hostPath
- op: add
  path: /spec/template/spec/volumes
  value:
    - name: cache
      hostPath:
        path: "/data/greenhouse"
- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - name: cache
      mountPath: /data
