#!/bin/bash

readonly IP=169.255.0.0
readonly SUBNET_MASK=24
readonly GW_IP=169.255.0.1
readonly CONTAINER_NETNS_LINK="/var/run/netns/$CNI_CONTAINERID"
readonly LOGFILE=/var/log/pfcni_multi.log

function main() {
    case "$CNI_COMMAND" in
        ADD)
            log "Received ADD command. CNI_ARGS: $CNI_ARGS"
            setup_netns
            # add_veth_pair
            setns_sriov_ifs
            gen_result_config
            ;;
        DELETE)
            log "Received DELETE command."
            ip netns del "$CNI_CONTAINERID" ||:
            ;;
    esac
}

function from_cni_args() {
    local var_name="${1:?}"
    sed -nE "s/.+?${var_name}=([^;]*?)(;.+?|$)/\1/p" <<< "$CNI_ARGS"
}

function setup_netns() {
    mkdir -p /var/run/netns
    ln -sfT "$CNI_NETNS" "$CONTAINER_NETNS_LINK"
}

function setns_sriov_ifs() {
  NUM_PF=1
  local sriov_pfs=( /sys/class/net/*/device/sriov_numvfs )
  if [ $sriov_pfs == "/sys/class/net/*/device/sriov_numvfs" ]; then
      log "FATAL: No sriov PFs found"
      exit 1
  fi

  local ifs_name
  PF_COUNTER=0
  for ifs in "${sriov_pfs[@]}"; do
    ifs_name="${ifs%%/device/*}"
    ifs_name="${ifs_name##*/}"
    if ip link set "$ifs_name" netns "$CNI_CONTAINERID"; then
      if timeout 5s bash -c "until ip netns exec $CNI_CONTAINERID ip link show $ifs_name > /dev/null; do sleep 1; done"; then
        log "Added pf: $ifs_name to netns $CNI_CONTAINERID"
        PF_COUNTER=$((PF_COUNTER+1))
        if [[ $PF_COUNTER -eq $NUM_PF ]]; then
          log "Allocated requested number of PFs"
          break
        fi
      fi
    fi
  done

  if [[ $PF_COUNTER -lt $NUM_PF ]]; then
    log "FATAL: Could not allocate enough PFs"
    exit 1
  fi
}

add_veth_pair() {
    local container_name
    container_name="$(from_cni_args K8S_POD_NAME)"
    local host_if="veth-1-${container_name}"
    local container_if="veth-2-${container_name}"
    ip link add "$container_if" type veth peer name "$host_if"
    ip link set "$host_if" up
    ip link set "$container_if" netns "$CNI_CONTAINERID"
    ip netns exec "$CNI_CONTAINERID" ip link set "$container_if" down
    ip netns exec "$CNI_CONTAINERID" ip link set "$container_if" name \
        "$CNI_IFNAME"
    ip netns exec "$CNI_CONTAINERID" ip link set "$container_if" up
    ip netns exec "$CNI_CONTAINERID" ip addr add "$IP/$SUBNET_MASK" \
        dev "$container_if"
}

function gen_result_config() {
  local mac
  mac="$(
    ip netns exec "$CNI_CONTAINERID" ip link show "$CNI_IFNAME" | \
        grep link | awk '{print $2}')"

  tee -a "$LOGFILE" <<-EOF
    {
        "cniVersion": "0.3.1",
        "interfaces": [
          {
            "name":"$CNI_IFNAME",
            "mac": "$mac",
            "sandbox": "$CNI_NETNS"
          }
        ],
        "ips": [
          {
            "version": "4",
            "address": "$IP/$SUBNET_MASK",
            "interface": 0
          }
        ]
    }
EOF
}

function log {
    echo "[$(date --rfc-3339=seconds)]: $*" >> "$LOGFILE"
}

main "$@"
