---
# Source: kube-prometheus-stack/templates/alertmanager/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-stack-kube-prom-alertmanager
  namespace: default
  labels:
    app: kube-prometheus-stack-alertmanager
    chart: kube-prometheus-stack-13.6.0
    release: "prometheus-stack"
    heritage: "Helm"
    group: kubevirtci
spec:
  selector:
    matchLabels:
      app: kube-prometheus-stack-alertmanager
      release: "prometheus-stack"
      self-monitor: "true"
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
  - port: web
    path: "/metrics"
---
# Source: kube-prometheus-stack/templates/exporters/core-dns/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-stack-kube-prom-coredns
  namespace: default
  labels:
    app: kube-prometheus-stack-coredns
    chart: kube-prometheus-stack-13.6.0
    release: "prometheus-stack"
    heritage: "Helm"
    group: kubevirtci
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: kube-prometheus-stack-coredns
      release: "prometheus-stack"
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
  - port: http-metrics
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
---
# Source: kube-prometheus-stack/templates/exporters/kube-etcd/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-stack-kube-prom-kube-etcd
  namespace: default
  labels:
    app: kube-prometheus-stack-kube-etcd
    chart: kube-prometheus-stack-13.6.0
    release: "prometheus-stack"
    heritage: "Helm"
    group: kubevirtci
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: kube-prometheus-stack-kube-etcd
      release: "prometheus-stack"
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
  - port: http-metrics
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
---
# Source: kube-prometheus-stack/templates/exporters/kube-state-metrics/serviceMonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-stack-kube-prom-kube-state-metrics
  namespace: default
  labels:
    app: kube-prometheus-stack-kube-state-metrics
    chart: kube-prometheus-stack-13.6.0
    release: "prometheus-stack"
    heritage: "Helm"
    group: kubevirtci
spec:
  jobLabel: app.kubernetes.io/name
  endpoints:
  - port: http
    honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/instance: prometheus-stack
---
# Source: kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-stack-kube-prom-kubelet
  namespace: default
  labels:
    app: kube-prometheus-stack-kubelet
    chart: kube-prometheus-stack-13.6.0
    release: "prometheus-stack"
    heritage: "Helm"
    group: kubevirtci
spec:
  endpoints:
  - port: https-metrics
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
  - port: https-metrics
    scheme: https
    path: /metrics/cadvisor
    honorLabels: true
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
  - port: https-metrics
    scheme: https
    path: /metrics/probes
    honorLabels: true
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kubelet
---
# Source: kube-prometheus-stack/templates/prometheus-operator/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-stack-kube-prom-operator
  namespace: default
  labels:
    app: kube-prometheus-stack-operator
    chart: kube-prometheus-stack-13.6.0
    release: "prometheus-stack"
    heritage: "Helm"
    group: kubevirtci
spec:
  endpoints:
  - port: http
    honorLabels: true
  selector:
    matchLabels:
      app: kube-prometheus-stack-operator
      release: "prometheus-stack"
  namespaceSelector:
    matchNames:
      - monitoring
---
# Source: kube-prometheus-stack/templates/prometheus/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-stack-kube-prom-prometheus
  namespace: default
  labels:
    app: kube-prometheus-stack-prometheus
    chart: kube-prometheus-stack-13.6.0
    release: "prometheus-stack"
    heritage: "Helm"
    group: kubevirtci
spec:
  selector:
    matchLabels:
      app: kube-prometheus-stack-prometheus
      release: "prometheus-stack"
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
  - port: web
    path: "/metrics"
---
# Source: prometheus-node-exporter/templates/monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-stack-kube-prom-node-exporter
    app.kubernetes.io/managed-by: Helm
    chart: kube-prometheus-stack-13.6.0
    heritage: "Helm"
    release: node-exporter
    group: kubevirtci
  name: prometheus-kube-prometheus-node-exporter
  namespace: default
spec:
  endpoints:
  - port: metrics
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: prometheus-node-exporter
      release: node-exporter