---
- name: Deploy the token-counter
  command: "oc -n {{prowNamespace}} apply -f -"
  args:
    stdin: "{{ lookup('template', '{{ role_path }}/templates/token-counter.yaml')}}"
- name: Deploy the prometheus config
  command: "oc -n {{prowNamespace}} apply -f -"
  args:
    stdin: "{{ lookup('template', '{{ role_path }}/templates/prometheus-config.yaml')}}"
- name: Deploy prometheus
  command: "oc -n {{prowNamespace}} apply -f -"
  args:
    stdin: "{{ lookup('template', '{{ role_path }}/templates/prometheus.yaml')}}"
- name: Deploy grafana dashboards
  command: "oc -n {{prowNamespace}} apply -f -"
  args:
    stdin: "{{ lookup('file', '{{ role_path }}/templates/dashboards.yaml')}}"
- name: Deploy the grafana config
  command: "oc -n {{prowNamespace}} apply -f -"
  args:
    stdin: "{{ lookup('template', '{{ role_path }}/templates/grafana-config.yaml')}}"
- name: Deploy grafana
  command: "oc -n {{prowNamespace}} apply -f -"
  args:
    stdin: "{{ lookup('template', '{{ role_path }}/templates/grafana.yaml')}}"
- name: Deploy grafana route
  command: "oc -n {{prowNamespace}} apply -f -"
  args:
    stdin: "{{ lookup('template', '{{ role_path }}/templates/routes.yaml')}}"
