FROM quay.io/kubevirtci/golang:v20251218-e7a7fc9 as builder
RUN cd /project-infra/ && \
    /usr/local/bin/runner.sh /bin/sh -ce "env GOPROXY=off go build -tags netgo -o /go/bin/release-blocker ./external-plugins/release-blocker"

FROM gcr.io/k8s-prow/git:v20240729-4f255edb07
COPY --from=builder /go/bin/release-blocker /usr/bin/release-blocker
ENTRYPOINT ["/usr/bin/release-blocker"]
