---
# setup data hostPath
- op: add
  path: /spec/template/spec/volumes/0
  value:
    name: storage
    hostPath:
      path: "/var/data/docker-mirror-proxy"
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/0
  value:
    name: storage
    mountPath: /docker_mirror_cache
