---
# Source: crds/khcheck.yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: khchecks.comcast.github.io
spec:
  group: comcast.github.io
  version: v1
  scope: Namespaced
  names:
    plural: khchecks
    singular: khcheck
    kind: KuberhealthyCheck
    shortNames:
      - khc

---
# Source: crds/khjob.yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: khjobs.comcast.github.io
spec:
  group: comcast.github.io
  version: v1
  scope: Namespaced
  names:
    plural: khjobs
    singular: khjob
    kind: KuberhealthyJob
    shortNames:
      - khj

---
# Source: crds/khstate.yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: khstates.comcast.github.io
spec:
  group: comcast.github.io
  version: v1
  scope: Namespaced
  names:
    plural: khstates
    singular: khstate
    kind: KuberhealthyState
    shortNames:
      - khs
  additionalPrinterColumns:
    - description: OK status
      JSONPath: .spec.OK
      name: OK
      type: string
    - description: Last Run
      JSONPath: .spec.LastRun
      name: Age LastRun
      type: date
    - description: Age
      JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
