apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds.yaml
- namespace.yaml
- serviceaccount.yaml
- service.yaml
- deployment.yaml

images:
- name: ghcr.io/grafana-operator/grafana-operator
  newName: ghcr.io/grafana-operator/grafana-operator
  newTag: v5.4.1
