apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: sinker
  labels:
    app: sinker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sinker
  template:
    metadata:
      labels:
        app: sinker
    spec:
      serviceAccountName: sinker
      containers:
      - name: sinker
        args:
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --dry-run=false
        image: gcr.io/k8s-prow/sinker:v20231221-73538ad97a
        env:
        # Use KUBECONFIG envvar rather than --kubeconfig flag in order to provide multiple configs to merge.
        - name: KUBECONFIG
          value: "/etc/kubeconfig/config:/etc/kubeconfig-build-test-infra-trusted/kubeconfig:/etc/kubeconfig-build-k8s-prow-builds/kubeconfig:/etc/kubeconfig-build-rules-k8s/kubeconfig:/etc/kubeconfig-eks-prow-build-cluster/kubeconfig::/etc/kubeconfig-k8s-infra-kops-prow-build/kubeconfig"
        # AWS_ variables needed to assume role to access the prow-build-cluster EKS cluster.
        - name: AWS_ROLE_ARN
          value: arn:aws:iam::468814281478:role/Prow-EKS-Admin
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /var/run/secrets/aws-iam-token/serviceaccount/token
        - name: AWS_REGION
          value: us-east-2
        ports:
        - name: metrics
          containerPort: 9090
        volumeMounts:
        - mountPath: /etc/kubeconfig
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/kubeconfig-build-test-infra-trusted
          name: kubeconfig-build-test-infra-trusted
          readOnly: true
        - mountPath: /etc/kubeconfig-build-k8s-prow-builds
          name: kubeconfig-build-k8s-prow-builds
          readOnly: true
        - mountPath: /etc/kubeconfig-build-rules-k8s
          name: kubeconfig-build-rules-k8s
          readOnly: true
        - mountPath: /etc/kubeconfig-eks-prow-build-cluster
          name: kubeconfig-eks-prow-build-cluster
          readOnly: true
        - mountPath: /etc/kubeconfig-k8s-infra-kops-prow-build
          name: kubeconfig-k8s-infra-kops-prow-build
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
        # AWS IAM token needed to assume role to access the prow-build-cluster EKS cluster.
        - name: aws-iam-token
          mountPath: /var/run/secrets/aws-iam-token/serviceaccount
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: kubeconfig
      - name: kubeconfig-build-test-infra-trusted
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-test-infra-trusted
      - name: kubeconfig-build-k8s-prow-builds
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-k8s-prow-builds
      - name: kubeconfig-build-rules-k8s
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-rules-k8s
      - name: kubeconfig-eks-prow-build-cluster
        secret:
          defaultMode: 420
          secretName: kubeconfig-eks-prow-build-cluster
      - name: kubeconfig-k8s-infra-kops-prow-build
        secret:
          defaultMode: 420
          secretName: kubeconfig-k8s-infra-kops-prow-build
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
      # AWS IAM token needed to assume role to access the prow-build-cluster EKS cluster.
      - name: aws-iam-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: sts.amazonaws.com
              expirationSeconds: 86400
              path: token
