apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: sinker
  labels:
    app: sinker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sinker
  template:
    metadata:
      labels:
        app: sinker
    spec:
      serviceAccountName: sinker
      containers:
      - name: sinker
        args:
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --dry-run=false
        image: gcr.io/k8s-prow/sinker:v20220908-f78f19e6a6
        env:
        # Use KUBECONFIG envvar rather than --kubeconfig flag in order to provide multiple configs to merge.
        - name: KUBECONFIG
          value: "/etc/kubeconfig/config:/etc/kubeconfig-build-test-infra-trusted/kubeconfig:/etc/kubeconfig-build-k8s-prow-builds/kubeconfig:/etc/kubeconfig-build-rules-k8s/kubeconfig"
        ports:
        - name: metrics
          containerPort: 9090
        volumeMounts:
        - mountPath: /etc/kubeconfig
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/kubeconfig-build-test-infra-trusted
          name: kubeconfig-build-test-infra-trusted
          readOnly: true
        - mountPath: /etc/kubeconfig-build-k8s-prow-builds
          name: kubeconfig-build-k8s-prow-builds
          readOnly: true
        - mountPath: /etc/kubeconfig-build-rules-k8s
          name: kubeconfig-build-rules-k8s
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: kubeconfig
      - name: kubeconfig-build-test-infra-trusted
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-test-infra-trusted
      - name: kubeconfig-build-k8s-prow-builds
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-k8s-prow-builds
      - name: kubeconfig-build-rules-k8s
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-rules-k8s
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
