apiVersion: v1
kind: ServiceAccount
metadata:
  name: "deck"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "hook"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "horologium"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "plank"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "caches"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "sinker"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "statusreconciler"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "tide"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "exporter"
---
