apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: admin
  namespace: "{{ prowNamespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
{% for user in prowAdmins %}
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ user }}
{% endfor %}
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: dedicated-admins
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: 'system:serviceaccounts:dedicated-admin'
