#jinja2: lstrip_blocks: "False", trim_blocks: "False"
apiVersion: v1
data:
  plugins.yaml: |
{{ prowPluginsConfig | indent(width=4, indentfirst=True) }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: "{{ prowNamespace }}"
