- hosts: localhost
  vars:
    kubevirtci_dir: /tmp/kubevirtci
    kubevirtci_provider: k8s-1.18
    kubeconfig: '{{ kubevirtci_dir }}/_ci-configs/{{ kubevirtci_provider }}/.kubeconfig'
    kubecontext: kubernetes-admin@kubernetes
  tasks:
    - name: Test remove manifest
      include_role:
        name: kubernetes_crud
      vars:
        default_namespace: test-namespace
        default_kubeconfig_path: '{{ kubeconfig }}'
        default_context: '{{ kubecontext }}'
        manifest_base: "{{ role_path }}/molecule/files/manifests"
        steps:
          - desc: Remove manifest
            op: remove_manifest
            manifest: "test-plain.yaml"

    - name: Gather info on created service
      k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kubecontext }}"
        api_version: v1
        kind: Service
        namespace: test-namespace
        name: test-service
      register: query

    - name: Verify service exists
      assert:
        that: query.resources == []
        success_msg: "Service correctly removed"
        fail_msg: "Service still exists"

    - name: Test remove namespace
      include_role:
        name: kubernetes_crud
      vars:
        default_kubeconfig_path: '{{ kubeconfig }}'
        default_context: '{{ kubecontext }}'
        manifest_base: "{{ role_path }}/molecule/files/manifests"
        steps:
          - desc: Remove namespace
            op: remove_namespace
            namespace: test-namespace

    - name: Gather info on created namespace
      k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kubecontext }}"
        api_version: v1
        kind: Namespace
        name: test-namespace
      register: query

    - name: Verify namespace does not exists
      assert:
        that: query.resources == []
        success_msg: "Namespace correctly removed"
        fail_msg: "Namespace still exists"

