- hosts: localhost
  vars:
    kubevirtci_dir: /tmp/kubevirtci
    kubevirtci_provider: k8s-1.18
    kubeconfig: '{{ kubevirtci_dir }}/_ci-configs/{{ kubevirtci_provider }}/.kubeconfig'
    kubecontext: kubernetes-admin@kubernetes
  tasks:
    - name: Test namespace creation
      include_role:
        name: kubernetes_crud
      vars:
        memory_limit: 512Mi
        default_kubeconfig_path: '{{ kubeconfig }}'
        default_namespace: test-namespace
        manifest_base: "{{ role_path }}/molecule/files/manifests"
        default_context: '{{ kubecontext }}'
        steps:
          - desc: Create test namespace
            namespace: test-namespace
            op: create_namespace

          - desc: Apply service from a manifest directly
            manifest: "test-plain.yaml"

          - desc: Apply LimitRange from manifest rendered from template
            manifest_template: "test-template.yml.j2"

          - desc: Apply Service account from invalid remote manifest (and testing validation override)
            manifest_url: "file://{{ role_path }}/molecule/files/manifests/test-url.yaml"
            # Needed as the manifest contains an invalid timestamp
            fatal_validation: false
            strict_validation: false

          - desc: Apply label to a node from inline manifest
            manifest_inline: |
              apiVersion: v1
              kind: Node
              metadata:
                name: node01
                labels:
                  test_label_key: test-label-value
