---
driver:
  name: delegated

platforms:
  - name: instance  # must be able to `ssh host`, edit your ~/.ssh/config
    options:
      managed: False

provisioner:
  name: ansible
  group_vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'

scenario:
  test_sequence:
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
