config_updater:
  maps:
    github/ci/prow/files/config.yaml:
      name: config
      namespace: kubevirt-prow
    github/ci/prow/files/jobs/**/*.yaml:
      name: job-config
      namespace: kubevirt-prow
    github/ci/prow/files/plugins.yaml:
      name: plugins
      namespace: kubevirt-prow
    github/ci/prow/files/labels.yaml:
      name: label-config
      namespace: kubevirt-prow

plugins:

  virtblocks:
  - trigger

  kubevirt:
  - size
  - label
  - hold
  - assign
  - blunderbuss
  - lifecycle
  - verify-owners
  - skip
  - override
  - wip
  - pony
  - dog
  - cat

  kubevirt/kubevirt:
  - trigger
  - release-note
  - owners-label
  - lgtm
  - approve

  kubevirt/containerized-data-importer:
  - release-note

  kubevirt/kubevirt-ansible:
  - release-note

  kubevirt/project-infra:
  - trigger
  - lgtm
  - approve
  - config-updater

  kubevirt/kubevirtci:
  - trigger
  - lgtm
  - approve

  kubevirt/kubevirt.github.io:
  - approve
  - lgtm
  - owners-label
  - trigger

  kubevirt/kubevirt-tutorial:
  - approve
  - lgtm
  - owners-label
  - trigger

  kubevirt/cloud-image-builder:
  - approve
  - lgtm
  - owners-label
  - trigger

  kubevirt/community:
  - approve
  - lgtm
  - owners-label

external_plugins:
  kubevirt:
  - name: needs-rebase
    events:
      - pull_request
  - name: cherrypicker

triggers:
- repos:
  - kubevirt/project-infra
  - kubevirt/kubevirtci
  - kubevirt/kubevirt
  - kubevirt/kubevirt.github.io
  - kubevirt/cloud-image-builder
  - kubevirt/kubevirt-tutorial
  trusted_org: kubevirt
- repos:
  - virtblocks/virtblocks

approve:
- repos:
  - kubevirt/project-infra
  - kubevirt/kubevirtci
  - kubevirt/kubevirt.github.io
  - kubevirt/cloud-image-builder
  - kubevirt/community
  - kubevirt/kubevirt-tutorial
  - kubevirt/kubevirt
  require_self_approval: true
  lgtm_acts_as_approve: false
  ignore_review_state: true

lgtm:
- repos:
  - kubevirt/project-infra
  - kubevirt/kubevirtci
  - kubevirt/kubevirt.github.io
  - kubevirt/cloud-image-builder
  - kubevirt/community
  - kubevirt/kubevirt-tutorial
  - kubevirt/kubevirt
  review_acts_as_lgtm: true
