config_updater:
  maps:
    github/ci/prow/files/config.yaml:
      name: config
    github/ci/prow/files/job-config.yaml:
      name: job-config
    github/ci/prow/files/plugins.yaml:
      name: plugins
    github/ci/prow/files/labels.yaml:
      name: label-config

plugins:
  kubevirt:
  - size
  - label
  - hold
  - assign
  - blunderbuss
  - lifecycle
  - verify-owners
  - wip

  kubevirt/kubevirt:
  - release-note
  - owners-label

  kubevirt/containerized-data-importer:
  - release-note

  kubevirt/kubevirt-ansible:
  - release-note

  kubevirt/project-infra:
  - trigger
  - lgtm
  - approve
  - config-updater
  - skip
  - override

  kubevirt/kubevirtci:
  - trigger
  - lgtm
  - approve
  - config-updater
  - skip
  - override

external_plugins:
  kubevirt:
  - name: needs-rebase
    events:
      - pull_request
  - name: cherrypicker

triggers:
- repos:
  - kubevirt/project-infra
  - kubevirt/kubevirtci
  trusted_org: kubevirt

approve:
- repos:
  - kubevirt/project-infra
  - kubevirt/kubevirtci
  require_self_approval: true
  lgtm_acts_as_approve: false
  ignore_review_state: true

lgtm:
- repos:
  - kubevirt/project-infra
  - kubevirt/kubevirtci
  review_acts_as_lgtm: true
