FROM quay.io/kubevirtci/golang:v20260830-8316684 as builder
ENV GO_MOD_PATH=/project-infra/go.mod
RUN cd /project-infra/ && \
    /usr/local/bin/entrypoint.sh /bin/sh -ce "env GOPROXY=off go build -tags netgo -o /go/bin/flake-report-creator ./robots/flake-report-creator"

FROM gcr.io/k8s-prow/git:v20240729-4f255edb07
COPY --from=builder /go/bin/flake-report-creator /usr/bin/flake-report-creator
ENTRYPOINT ["/usr/bin/flake-report-creator"]
