FROM docker.io/library/golang:1.20 as builder
WORKDIR /go/src/github.com/kubevirt/project-infra/
RUN mkdir -p /go/src/kubevirt/ && \
    cd /go/src/kubevirt/ && \
    git clone https://github.com/kubevirt/project-infra.git && \
    cd project-infra/ && \
    go mod vendor && \
    env GOPROXY=off GOFLAGS=-mod=vendor CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /go/bin/botreview ./external-plugins/botreview/main.go

FROM gcr.io/k8s-prow/git:v20240729-4f255edb07
COPY --from=builder /go/bin/botreview /usr/bin/botreview
ENTRYPOINT ["/usr/bin/botreview"]
