---
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    iam.gke.io/gcp-service-account: pusher@k8s-prow.iam.gserviceaccount.com
  name: pusher
  namespace: test-pods
---
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    iam.gke.io/gcp-service-account: testgrid-config-updater@k8s-testgrid.iam.gserviceaccount.com
  name: testgrid-config-updater
  namespace: test-pods
---
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    iam.gke.io/gcp-service-account: deployer@k8s-prow.iam.gserviceaccount.com
  name: deployer
  namespace: test-pods
---
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    iam.gke.io/gcp-service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  name: k8s-infra-gcr-promoter
  namespace: test-pods
---
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    iam.gke.io/gcp-service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod-bak.iam.gserviceaccount.com
  name: k8s-infra-gcr-promoter-bak
  namespace: test-pods
# TODO(fejta): https://github.com/kubernetes/test-infra/issues/15806
# * Run experiment/workload-identity/bind-service-accounts.sh on the above
# * Config service account on job
# Do the same for the following:
# k8s-artifacts-graveyard-service-account
# k8s-artifacts-prod-bak-service-account
# k8s-gcr-prod-service-account
# service-account
