---
# sets up dynamic provisioned PV
- op: add
  path: /spec/template/spec/volumes
  value:
    - name: cache
      persistentVolumeClaim:
        claimName: greenhouse
- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - name: cache
      mountPath: /data
