# allow crier to access remote clusters
- op: add
  path: /spec/template/spec/containers/0/args/11
  value: --kubeconfig=/etc/remote_cluster_config/config
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/6
  value:
    mountPath: /etc/remote_cluster_config
    name: kubeconfig
    readOnly: true
- op: add
  path: /spec/template/spec/volumes/6
  value:
    name: kubeconfig
    secret:
      defaultMode: 420
      secretName: kubeconfig
