---
- name: Deploy the prometheus config
  command: "oc -n {{prowNamespace}} apply -f -"
  args:
    stdin: "{{ lookup('template', '{{ role_path }}/templates/prometheus-config.yaml')}}"
- name: Deploy prometheus
  command: "oc -n {{prowNamespace}} apply -f -"
  args:
    stdin: "{{ lookup('template', '{{ role_path }}/templates/prometheus.yaml')}}"
- name: Deploy the grafana config
  command: "oc -n {{prowNamespace}} apply -f -"
  args:
    stdin: "{{ lookup('template', '{{ role_path }}/templates/grafana-config.yaml')}}"
- name: Deploy grafana
  command: "oc -n {{prowNamespace}} apply -f -"
  args:
    stdin: "{{ lookup('template', '{{ role_path }}/templates/grafana.yaml')}}"
