---
- name: Update basic-auth secret for push gateway
  openshift_raw:
    state: present
    namespace: "{{ prowNamespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: basic-auth
      type: Opaque            
      data:
        htaccess: "{{ str | b64encode }}"
  vars:
    str: "{{pushGatewayUser}}:{{pushGatewayPass | password_hash('sha512')}}"
- name: Update nginx config
  openshift_raw:
    state: present
    namespace: "{{ prowNamespace }}"
    definition: "{{ lookup('file', '{{ role_path }}/files/prometheus-proxy-config.yaml') | from_yaml }}"
  state: present
- name: Deploy pushgateway
  openshift_raw:
    state: present
    namespace: "{{ prowNamespace }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/pushgateway.yaml') | from_yaml }}"
  state: present
- name: Deploy pushgateway service
  openshift_raw:
    state: present
    namespace: "{{ prowNamespace }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/pushgateway-service.yaml') | from_yaml }}"
  state: present
- name: Update prometheus config
  openshift_raw:
    state: present
    namespace: "{{ prowNamespace }}"
    definition: "{{ lookup('file', '{{ role_path }}/files/prometheus-config.yaml') | from_yaml }}"
  state: present
- name: Deploy prometheus
  command: "oc -n {{prowNamespace}} apply -f -"
  args:
    stdin: "{{ lookup('template', '{{ role_path }}/templates/prometheus.yaml')}}"
- name: Deploy prometheus service
  openshift_raw:
    state: present
    namespace: "{{ prowNamespace }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/prometheus-service.yaml') | from_yaml }}"
  state: present
- name: Deploy prometheus proxy
  openshift_raw:
    state: present
    namespace: "{{ prowNamespace }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/prometheus-proxy.yaml') | from_yaml }}"
  state: present
- name: Deploy prometheus proxy service
  openshift_raw:
    state: present
    namespace: "{{ prowNamespace }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/prometheus-proxy-service.yaml') | from_yaml }}"
  state: present
- name: Deploy pushgateway proxy service
  openshift_raw:
    state: present
    namespace: "{{ prowNamespace }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/pushgateway-proxy-service.yaml') | from_yaml }}"
  state: present
- name: Deploy prometheus route
  openshift_raw:
    state: present
    namespace: "{{ prowNamespace }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/prometheus-route.yaml') | from_yaml }}"
  state: present
- name: Deploy pushgateway route
  openshift_raw:
    state: present
    namespace: "{{ prowNamespace }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/pushgateway-route.yaml') | from_yaml }}"
  state: present

