---
# Source: kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: prometheus-stack-kube-prom-alertmanager
  namespace: default
  labels:
    app: kube-prometheus-stack-alertmanager

    chart: kube-prometheus-stack-13.6.0
    release: "prometheus-stack"
    heritage: "Helm"
    group: kubevirtci
spec:
  image: quay.io/prometheus/alertmanager:v0.21.0
  version: v0.21.0
  replicas: 1
  listenLocal: false
  serviceAccountName: prometheus-stack-kube-prom-alertmanager
  externalUrl: http://prometheus-stack-kube-prom-alertmanager.default:9093
  paused: false
  logFormat: "logfmt"
  logLevel: "info"
  retention: "120h"
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: kubevirtci
  alertmanagerConfigNamespaceSelector: {}
  resources:
    limits:
      cpu: 10m
      memory: 400Mi
    requests:
      cpu: 10m
      memory: 400Mi
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  portName: web
