FROM quay.io/kubevirtci/golang:v20260319-c8f1db8 as builder
RUN cd /project-infra/ && \
    /usr/local/bin/runner.sh /bin/sh -ce "env GOPROXY=off go build -tags netgo -o /go/bin/indexpagecreator ./robots/indexpagecreator"

FROM gcr.io/k8s-prow/git:v20240729-4f255edb07
COPY --from=builder /go/bin/indexpagecreator /usr/bin/indexpagecreator
ENTRYPOINT ["/usr/bin/indexpagecreator"]
