apiVersion: v1
kind: Route
metadata:
  name: jenkins
  namespace: "{{ prowNamespace }}"
spec:
  host: "{{ jenkinsUrl }}"
  path: /
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: jenkins
    weight: 100
  wildcardPolicy: None
