apiVersion: v1
kind: Service
metadata:
  name: "jenkins"
  namespace: "{{ prowNamespace }}"
spec:
  selector:
    app: jenkins
  ports:
  - name: jenkins
    port: 80
    targetPort: 8080
  type: ClusterIP
