apiVersion: v1
kind: Service
metadata:
  name: "jnlp"
  namespace: "{{ prowNamespace }}"
spec:
  selector:
    app: jenkins
  ports:
  - name: jnlp
    port: 50000
    targetPort: 50000
  type: ClusterIP
