# Test provisioning
testinfra_dir: /tmp/test-infra
project_infra_root: /workspace/repos/project-infra-main

kubeconfig_path: '/root/.kube/config'
secrets_dir: '{{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/secrets/'
components_dir: '{{ project_infra_root }}/github/ci/prow-deploy/kustom/components'
kind:
  cluster_config: '/workspace/cluster.yaml'
  image_tag: v1.21.1


node_name: node01

SRIOVNodes:
- name: '{{ node_name }}'
  capacity: 2

ansible_python_interpreter: /usr/bin/python3

githubUnprivileged:
  token: "test"
