---
- hosts: local
  gather_facts: False
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  tasks:
    - name: include prow-deploy role
      include_role:
        name: prow-deploy
