---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-config
type: Opaque
stringData:
  grafana.ini: |
    # nothing right now
    [security]
    admin_user = {{ grafanaUser }}
    admin_password = {{ grafanaPassword }}

    [auth.anonymous]
    enabled = true
    org_name = Main Org.
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus
      version: 1
