---
kind: Service
apiVersion: v1
metadata:
  name: grafana
  labels:
    kubernetes.io/name: "Prometheus"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
