---
kind: Service
apiVersion: v1
metadata:
  name: prometheus
  labels:
    kubernetes.io/name: "Prometheus"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
