apiVersion: v1
kind: Route
metadata:
  name: prometheus
spec:
  host: "{{ prometheusGatewayUrl }}"
  path: /
  tls:
    termination: edge
  to:
    kind: Service
    name: prometheus-proxy
    weight: 100
  wildcardPolicy: None
