apiVersion: v1
kind: Service
metadata:
  name: prometheus-proxy
  labels:
    app: prometheus-proxy
spec:
  ports:
  - name: prometheus-proxy
    port: 80
    targetPort: prometheus
  type: NodePort
  selector:
    app: prometheus-proxy
