---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'pushgateway'
        static_configs:
          - targets: ['pushgateway']
      - job_name: 'bazel-cache'
        metrics_path: /prometheus
        static_configs:
          - targets: ['bazel-cache-metrics']
      - job_name: 'token-counter'
        static_configs:
          - targets: ['token-counter-metrics']
