apiVersion: v1
kind: Service
metadata:
  name: pushgateway-external
  labels:
    app: pushgateway-external
spec:
  ports:
  - name: pushgateway-external
    port: 80
    targetPort: http-secured
  type: NodePort
  selector:
    app: pushgateway
