apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pushgateway
  labels:
    app: pushgateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 2001
      containers:
      - name: pushgateway
        image: prom/pushgateway:v0.4.0
        ports:
          - name: http-unsecured
            containerPort: 9091
      - name: nginx
        ports:
          - name: http-secured
            containerPort: 8081
        image: nginx:1
        volumeMounts:
        - name: htaccess
          mountPath: /etc/security/
          readOnly: true
        - name: config-volume
          mountPath: /etc/nginx/
        - name: cache
          mountPath: /var/cache/nginx
      volumes:
      - name: config-volume
        configMap:
          name: pushgateway-proxy-config
      - name: cache
        emptyDir: {}
      - name: htaccess
        secret:
          secretName: basic-auth
