apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pushgateway
  labels:
    app: pushgateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 2001
      containers:
      - name: pushgateway
        image: prom/pushgateway:v0.4.0
        ports:
          - name: http-unsecured
            containerPort: 9091
