apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  labels:
    app: pushgateway
spec:
  ports:
  - name: pushgateway
    port: 80
    targetPort: http-unsecured
  type: NodePort
  selector:
    app: pushgateway
