FROM quay.io/kubevirtci/golang:v20251218-e7a7fc9 as builder
RUN cd /project-infra/ && \
    /usr/local/bin/runner.sh /bin/sh -ce "env GOPROXY=off go build -tags netgo -o /go/bin/flakefinder ./robots/flakefinder"

FROM gcr.io/k8s-prow/git:v20240729-4f255edb07
COPY --from=builder /go/bin/flakefinder /usr/bin/flakefinder
ENTRYPOINT ["/usr/bin/flakefinder"]
