# Force ingress controller to run on a specific node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
spec:
  template:
    spec:
      hostNetwork: true
      nodeSelector:
        role: ingress-controller
