apiVersion: batch/v1
kind: CronJob
metadata:
  name: branch-protector
spec:
  schedule: "54 * * * *"  # Every hour at 54 minutes past the hour
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: branchprotector
    spec:
      template:
        spec:
          containers:
            - name: branchprotector
              image: us-docker.pkg.dev/k8s-infra-prow/images/branchprotector:v20260714-0633879af
              args:
                - --config-path=/etc/config/config.yaml
                - --job-config-path=/etc/job-config
                - --github-endpoint=http://ghproxy
                - --github-endpoint=https://api.github.com
                - --github-app-id=$(GITHUB_APP_ID)
                - --github-app-private-key-path=/etc/github/cert
                - --confirm
              env:
                - name: GITHUB_APP_ID
                  valueFrom:
                    secretKeyRef:
                      name: github-token
                      key: appid
              volumeMounts:
                - name: config
                  mountPath: /etc/config
                  readOnly: true
                - name: job-config
                  mountPath: /etc/job-config
                  readOnly: true
                - name: github-token
                  mountPath: /etc/github
                  readOnly: true
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ALL]
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: config
            - name: job-config
              configMap:
                name: job-config
            - name: github-token
              secret:
                secretName: github-token
