apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-daemon-mirror-config
data:
  docker: |
    DOCKER_OPTS="${DOCKER_OPTS} --data-root=/docker-graph"
    DOCKER_OPTS="${DOCKER_OPTS} --registry-mirror=http://docker-mirror.kubevirt-prow.svc:5000 --insecure-registry=http://docker-mirror.kubevirt-prow.svc:5000"
    DOCKER_OPTS="${DOCKER_OPTS} --mtu=1450"
    DOCKER_OPTS="${DOCKER_OPTS} --ipv6"
    DOCKER_OPTS="${DOCKER_OPTS} --fixed-cidr-v6 2001:db8:1::/64"

  docker-proxy: |
    DOCKER_OPTS="${DOCKER_OPTS} --data-root=/docker-graph"
    DOCKER_OPTS="${DOCKER_OPTS} --mtu=1450"
    DOCKER_OPTS="${DOCKER_OPTS} --ipv6"
    DOCKER_OPTS="${DOCKER_OPTS} --fixed-cidr-v6 2001:db8:1::/64"
    export http_proxy=http://docker-mirror-proxy.kubevirt-prow.svc:3128
    export https_proxy=http://docker-mirror-proxy.kubevirt-prow.svc:3128
