apiVersion: v1
kind: ConfigMap
metadata:
  name: prow-coverage-config
data:
  config.yaml: |
    defaults:
      namespace: kubevirt-prow-jobs
      image: "quay.io/kubevirtci/covreport:latest"
      cluster: kubevirt-prow-control-plane
      coverageThreshold: 70
      githubTokenSecret: commenter-oauth-token
      env:
        GO_MOD_PATH: go.mod
        GOTOOLCHAIN: local
      timeoutMinutes: 120
      gracePeriodSeconds: 15
      utilityImages:
        cloneRefs: "us-docker.pkg.dev/k8s-infra-prow/images/clonerefs:v20260702-ef12e757d"
        initUpload: "us-docker.pkg.dev/k8s-infra-prow/images/initupload:v20260702-ef12e757d"
        entrypoint: "us-docker.pkg.dev/k8s-infra-prow/images/entrypoint:v20260702-ef12e757d"
        sidecar: "us-docker.pkg.dev/k8s-infra-prow/images/sidecar:v20260702-ef12e757d"
      gcs:
        bucket: kubevirt-prow
        pathStrategy: explicit
        credentialsSecret: gcs
    repos:
      kubevirt/project-infra:
        testPackages: "./external-plugins/... ./releng/... ./robots/... ./cmd/... ./pkg/..."
        coverageThreshold: 25
      kubevirt/ci-health:
        testPackages: "./pkg/... ./cmd/..."
