apiVersion: apps/v1
kind: Deployment
metadata:
  name: coverage
  labels:
    app: coverage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prow-coverage
  template:
    metadata:
      labels:
        app: prow-coverage
    spec:
      serviceAccountName: prow-coverage
      terminationGracePeriodSeconds: 180
      containers:
        - name: coverage
          image: quay.io/kubevirtci/coverage:v20260506-920f941
          imagePullPolicy: IfNotPresent
          args:
            - --dry-run=false
            - --config=/etc/coverage/config.yaml
            - --github-token-path=/etc/github/oauth
            - --github-endpoint=http://ghproxy
            - --github-endpoint=https://api.github.com
            - --hmac-secret-file=/etc/webhook/hmac
          ports:
            - name: http
              containerPort: 9901
          volumeMounts:
            - name: hmac
              mountPath: /etc/webhook
              readOnly: true
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: config
              mountPath: /etc/coverage
              readOnly: true
      volumes:
        - name: hmac
          secret:
            secretName: hmac-token
        - name: oauth
          secret:
            secretName: oauth-token
        - name: config
          configMap:
            name: prow-coverage-config
