apiVersion: apps/v1
kind: Deployment
metadata:
  name: rehearse
  labels:
    app: rehearse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prow-rehearse
  template:
    metadata:
      labels:
        app: prow-rehearse
    spec:
      serviceAccountName: prow-rehearse
      terminationGracePeriodSeconds: 180
      containers:
        - name: rehearse
          image: quay.io/kubevirtci/rehearse:v202607231917-ca75c4e
          imagePullPolicy: IfNotPresent
          args:
            - --dry-run=false
            - --github-endpoint=http://ghproxy
            - --github-endpoint=https://api.github.com
            - --github-app-id=$(GITHUB_APP_ID)
            - --github-app-private-key-path=/etc/github/cert
            - --cache-dir=/var/run/cache
            - --jobs-config-base=github/ci/prow-deploy/files/jobs
            - --prow-config-path=github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
            - --always-run=false
          env:
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: appid
          ports:
            - name: http
              containerPort: 9900
          volumeMounts:
            - name: hmac
              mountPath: /etc/webhook
              readOnly: true
            - name: github-token
              mountPath: /etc/github
              readOnly: true
            - name: plugins
              mountPath: /etc/plugins
              readOnly: true
            - name: cache
              mountPath: /var/run/cache
              readOnly: false
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: hmac
          secret:
            secretName: hmac-token
        - name: github-token
          secret:
            secretName: github-token
        - name: plugins
          configMap:
            name: plugins
        - name: cache
          emptyDir: {}
