---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: referee
  labels:
    app: referee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: referee
  template:
    metadata:
      labels:
        app: referee
    spec:
      terminationGracePeriodSeconds: 180
      containers:
      - name: referee
        image: quay.io/kubevirtci/referee:v20260716-a2b9efe
        args:
        - --dry-run=false
        - --max-no-of-allowed-retest-comments=3
        - --port=9900
        # Not using KubeVirt CI Prow GitHub App Credentials because the
        # trigger plugin ignore comments from its own bot user.
        - --github-token-path=/etc/github/token
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        ports:
        - name: http
          containerPort: 9900
        volumeMounts:
        - name: hmac
          mountPath: /etc/webhook
          readOnly: true
        - name: github-token
          mountPath: /etc/github
          readOnly: true
        - name: plugins
          mountPath: /etc/plugins
          readOnly: true
        - name: cache
          mountPath: /var/run/cache
          readOnly: false
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: hmac
        secret:
          secretName: hmac-token
      - name: github-token
        secret:
          secretName: commenter-oauth-token
          items:
            - key: oauth
              path: token
      - name: plugins
        configMap:
          name: plugins
      - name: cache
        emptyDir: {}
