apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-blocker
  labels:
    app: release-blocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: release-blocker
  template:
    metadata:
      labels:
        app: release-blocker
    spec:
      terminationGracePeriodSeconds: 180
      containers:
      - name: release-blocker
        image: quay.io/kubevirtci/release-blocker:v20260716-ff8cd14
        imagePullPolicy: IfNotPresent
        args:
        - --dry-run=false
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --github-app-id=$(GITHUB_APP_ID)
        - --github-app-private-key-path=/etc/github/cert
        env:
          - name: GITHUB_APP_ID
            valueFrom:
              secretKeyRef:
                name: github-token
                key: appid
        ports:
          - name: http
            containerPort: 8888
        volumeMounts:
        - name: hmac
          mountPath: /etc/webhook
          readOnly: true
        - name: github-token
          mountPath: /etc/github
          readOnly: true
        - name: plugins
          mountPath: /etc/plugins
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: hmac
        secret:
          secretName: hmac-token
      - name: github-token
        secret:
          secretName: github-token
      - name: plugins
        configMap:
          name: plugins
