apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-blocker
  labels:
    app: release-blocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: release-blocker
  template:
    metadata:
      labels:
        app: release-blocker
    spec:
      terminationGracePeriodSeconds: 180
      containers:
      - name: release-blocker
        image: quay.io/kubevirtci/release-blocker:v20220815-ab4bb7e6
        imagePullPolicy: Always
        args:
        - --dry-run=false
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --github-token-path=/etc/github/oauth
        ports:
          - name: http
            containerPort: 8888
        volumeMounts:
        - name: hmac
          mountPath: /etc/webhook
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: plugins
          mountPath: /etc/plugins
          readOnly: true
      volumes:
      - name: hmac
        secret:
          secretName: hmac-token
      - name: oauth
        secret:
          secretName: oauth-token
      - name: plugins
        configMap:
          name: plugins
