---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: test-subset
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-subset
rules:
  - apiGroups:
      - prow.k8s.io
    resources:
      - prowjobs
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-subset
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: test-subset
  kind: ClusterRole
subjects:
  - kind: ServiceAccount
    name: test-subset
    namespace: default
