FROM quay.io/kubevirtci/golang:v20230801-94954c0

ENV GIMME_GO_VERSION=1.19

RUN set -x && \
    /usr/local/bin/runner.sh /bin/sh -ce 'go install github.com/onsi/ginkgo/v2/ginkgo@v2.9.2' && \
    mv /root/go/bin/ginkgo /usr/local/bin/

RUN set -x && \
    git clone https://github.com/dhiller/project-infra && \
    cd ./project-infra && \
    git checkout add-consume-filter-test-file && \
    /usr/local/bin/runner.sh /bin/sh -ce 'go install ./robots/cmd/test-label-analyzer' && \
    mv /root/go/bin/test-label-analyzer /usr/local/bin/ && \
    /usr/local/bin/runner.sh /bin/sh -ce 'go clean -cache -modcache' && \
    cd .. && rm -rf ./project-infra

ENTRYPOINT ["/usr/local/bin/test-label-analyzer"]
