resources:
- ../../base
- ./manifests/ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: grafana
  namespace: monitoring
  behavior: replace
  files:
  - ./secrets/grafana/admin-password
  - ./secrets/grafana/admin-user
  - ./secrets/grafana/client-id
  - ./secrets/grafana/client-secret
  - ./secrets/grafana/prom_bearer_token

