FROM quay.io/kubevirtci/golang:v20251218-e7a7fc9 as builder
RUN cd /project-infra/ && \
    /usr/local/bin/runner.sh /bin/sh -c "env GOPROXY=off go build -tags netgo -o /go/bin/release-tool ./releng/release-tool"

FROM quay.io/kubevirtci/release-tool-base:v20250214-0d9df61
COPY ./entrypoint.sh /usr/sbin/entrypoint.sh
COPY --from=builder /go/bin/release-tool /usr/bin/release-tool
ENTRYPOINT ["/usr/sbin/entrypoint.sh"]
