FROM quay.io/kubevirtci/golang:v20250701-f32dbda as builder
ENV GOPROXY=https://proxy.golang.org|direct \
    GOFLAGS="-mod=vendor -ldflags=-extldflags=\"-static\"" \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
ENV GIMME_GO_VERSION=1.25.1
RUN if [ ! -d /project-infra ]; then git clone https://github.com/kubevirt/project-infra.git /project-infra; fi && \
    cd /project-infra/ && \
    /usr/local/bin/runner.sh /bin/sh -c "env GOPROXY=off go build -tags netgo -o /go/bin/release-tool ./releng/release-tool"

FROM quay.io/kubevirtci/release-tool-base:v20250214-0d9df61
COPY ./entrypoint.sh /usr/sbin/entrypoint.sh
COPY --from=builder /go/bin/release-tool /usr/bin/release-tool
ENTRYPOINT ["/usr/sbin/entrypoint.sh"]
