---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    group: kubevirtci
  name: kubernetes-apps
spec:
  groups:
  - name: kubernetes-apps
    rules:
    - alert: KubePodNotReady
      annotations:
        message: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready
          state for longer than 1h30m.'
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodnotready
      expr: |
        sum by (namespace, pod) (kube_pod_status_phase{job="kube-state-metrics", phase=~"Pending|Unknown"}) > 0
      for: 90m
      labels:
        severity: critical
        namespace: monitoring
