FROM quay.io/kubevirtci/golang:v20250701-f32dbda as builder
RUN cd /project-infra/ && \
    /usr/local/bin/runner.sh /bin/sh -ce "env GOPROXY=off go build -tags netgo -o /go/bin/test-report ./robots/cmd/test-report"

FROM gcr.io/k8s-prow/git:v20240729-4f255edb07
COPY --from=builder /go/bin/test-report /usr/bin/test-report
ENTRYPOINT ["/usr/bin/test-report"]
