# Removes deprecated  --redirect-http-to=
- op: remove
  path: /spec/template/spec/containers/0/args/2
- op: remove
  path: /spec/template/spec/containers/0/livenessProbe
- op: remove
  path: /spec/template/spec/containers/0/readinessProbe
