---
# allow ghproxy to be scheduled on any node
- op: remove
  path: /spec/template/spec/tolerations
- op: remove
  path: /spec/template/spec/nodeSelector
- op: add
  path: /spec/strategy
  value:
    rollingUpdate:
      maxUnavailable: 1
