# REmoves hisotry-uri and status-path which point to a
# remote google storage location
- op: remove
  path: /spec/template/spec/containers/0/args/7
- op: remove
  path: /spec/template/spec/containers/0/args/6
