kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "exporter"
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "exporter"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "exporter"
subjects:
- kind: ServiceAccount
  name: "exporter"
  namespace: "{{prowNamespace}}"
