apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pushgateway
  labels:
    app: pushgateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      nodeSelector:
        type: vm
        zone: ci
      containers:
      - name: pushgateway
        image: prom/pushgateway:v0.7.0
        ports:
          - name: http
            containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  labels:
    app: pushgateway
    metrics: "true"
spec:
  ports:
  - name: pushgateway
    port: 80
    targetPort: http
  selector:
    app: pushgateway
