---
apiVersion: v1
kind: Route
metadata:
  name: hook
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  host: "{{ prowUrl }}"
  path: /hook
  tls:
    termination: edge
  to:
    kind: Service
    name: hook
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: Route
metadata:
  name: deck
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  host: "{{ deckUrl }}"
  tls:
    termination: edge
  to:
    kind: Service
    name: deck
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: Route
metadata:
  name: gcsweb
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  host: "{{ gcswebUrl }}"
  tls:
    termination: edge
  to:
    kind: Service
    name: gcsweb
    weight: 100
  wildcardPolicy: None
