---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mirror-proxy
  namespace: kubevirt-prow
spec:
  selector:
    matchLabels:
      app: docker-mirror-proxy
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: docker-mirror-proxy
    spec:
      terminationGracePeriodSeconds: 180
      containers:
      - name: mirror-proxy
        image: ghcr.io/rpardini/docker-registry-proxy:0.6.2
        env:
        - name: ENABLE_MANIFEST_CACHE
          value: "true"
        - name: ALLOW_PUSH
          value: "true"
        - name: PROXY_CONNECT_TIMEOUT
          value: "1200s"
        - name: PROXY_CONNECT_READ_TIMEOUT
          value: "1200s"
        - name: PROXY_CONNECT_CONNECT_TIMEOUT
          value: "1200s"
        - name: PROXY_CONNECT_SEND_TIMEOUT
          value: "1200s"
        - name: SEND_TIMEOUT
          value: "1200s"
        - name: CLIENT_BODY_TIMEOUT
          value: "1200s"
        - name: CLIENT_HEADER_TIMEOUT
          value: "1200s"
        - name: PROXY_READ_TIMEOUT
          value: "1200s"
        - name: PROXY_SEND_TIMEOUT
          value: "1200s"
        volumeMounts:
        - name: ca-public
          mountPath: /ca/ca.crt
          subPath: ca.crt
          readOnly: true
        - name: ca-private
          mountPath: /ca/ca.key
          subPath: ca.key
          readOnly: true
        ports:
          - name: http
            containerPort: 3128
            protocol: TCP
        resources:
          requests:
            cpu: 300m
            memory: 3Gi
          limits:
            cpu: 300m
            memory: 3Gi
      volumes:
      - name: ca-public
        configMap:
          name: mirror-proxy-config
      - name: ca-private
        secret:
          secretName: docker-mirror-proxy
